# for one device, can be given like this:
hosts:
  - device: 10.13.84.74 
    username : root
    passwd: Juniper123
  - device: 10.13.84.75 
    username : root
    passwd: Juniper123
tests:
  - vsrx_sec_config_audit.yml 

# local:
#   - STORED
