

dqenet_device_junos_cli_username: "root"
dqenet_device_junos_cli_password: "Embe1mpls"
dqenet_device_junos_cli_user_privkey_file: "{{ lookup('env','HOME') + '/.ssh/id_rsa' }}"
dqenet_device_junos_cli_user_pubkey_file: "{{ dqenet_device_junos_cli_user_privkey_file}}.pub"

dqenet_device_junos_junos_config_remove_existing : true

# set this variable to false if you do not want to load custom config for QFX
dqenet_device_junos_junos_config_apply_merge : false

dqenet_device_junos_cli_access_check: true
dqenet_device_junos_commit_check: true
dqenet_device_junos_commit: false


# Directory where Junos config files for QFX are generated
dqnet_device_data_dir: "{{ lookup('env', 'DQNET_DEVICE_DATA_DIR') | default('/var/tmp/DQE_DATA', true) }}"
dqenet_device_junos_config_base_dir: "{{ dqnet_device_data_dir }}/junos_config"
dqenet_device_junos_config_diff_dir: "{{ dqnet_device_data_dir }}/junos_config_diff"
dqenet_device_junos_config_err_dir: "{{ dqnet_device_data_dir }}/junos_config_err"

dqenet_device_junos_config_filename_prefix: junos_config

dqnet_server_gui_url_list: [ "http://localhost" ]
dqnet_server_api_username: "admin"
dqnet_server_api_passwsord: "admin"



# JSNAPy-related variables for Audit-Diff Analysis
jsnapy_home_dir: "{{ playbook_dir }}/files/jsnapy" 
jsnapy_config_file_dir_path: "{{ jsnapy_home_dir }}"
jsnapy_snapshot_dir_path: "{{ jsnapy_config_file_dir_path }}/snapshots"
jsnapy_test_file_dir_path: "{{ jsnapy_config_file_dir_path }}/testfiles"
jsnapy_log_dir_path: /var/tmp/jsnapy_log
jsnapy_config_j2_file_path: jsnapy.cfg.j2

# jsnapy_sec_config_audit_conf_file : files/jsnapy/config_check.yml
jsnapy_config_audit_conf_file : config_check.yml
# jsnapy_config_audit_test_file: vsrx_sec_config_audit.yml
jsnapy_config_audit_test_file: mx_protocols_config_audit.yml


# model_group_template_map_file_name: Model_Groups.csv
model_group_template_map_file_name: Model_Groups.xlsx

ansible_python_path: python3
ansible_python_interpreter: "{{ ansible_python_path }}"

