---
###################################################################################
#
# Copyright 2020 Juniper Networks, Inc. All rights reserved.
# Licensed under the Juniper Networks Script Software License (the "License").
# You may not use this script file except in compliance with the License, which is 
# located at http://www.juniper.net/support/legal/scriptlicense/
# Unless required by applicable law or otherwise agreed to in writing by the 
# parties, software distributed under the License is distri buted on an 
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express 
# or implied.
#
##################################################################################
#
# Author        : Subrata Mazumdar, Juniper Networks Professional Services
# Contact       : subratam@juniper.net
# Company       : Juniper Networks
#
#
# Description   : 
#
#
# tasks file for vnfstack


- name: run the jnpr_vnfstack module for VNF-related Heat stack  info
  jnpr_vnfstack:
    # allowed actions:
    #     create-stack,list-stack,show-stack,wait-for-stack,delete-stack,
    #     show-stack-server-mgmt-ip-list,
    #     show-stack-server-uuid-list,
    #     show-stack-server-name-list,
    #     show-stack-server-data-list,
    #     show-stack-server-name-mgmtip-list,
    #     get-vnf-name,
    #
    # action: 'get-os-token'
    # action: 'show-stack-server-name-mgmtip-list'
    action: "{{ action }}"


    nested_depth: "{{ nested_depth }}"
    wait_for_stack: "{{ wait_for_stack }}"
    stack_name: "{{ stack_name }}"

    server_mgmt_vn_name: "{{ server_mgmt_vn_name }}"
    server_image_uuid: "{{ server_image_uuid }}"
    server_image_name: "{{ server_image_name }}"

    os_server_name: "{{ os_server_name }}"
    os_server_uuid: "{{ os_server_uuid }}"

    os_auth_url: "{{ os_auth_url }}"
    os_auth_domain: "{{ os_auth_domain }}"
    os_tenant_name: "{{ os_tenant_name }}"
    # os_version: "{{ os_version }}"
    os_username: "{{ os_username }}"
    os_password: "{{ os_password }}"

  register: task_result

- name: set fact action result 
  set_fact:
    vnfstack_action_result: "{{ task_result }}"

- name: dump test output
  debug:
    # with_items: "{{ task_result.data.output.values() }}"
    msg: "{{ task_result }}"



