tests_include:
  - test_protocols_bgp
  - test_routing_options

test_protocols_bgp:
  - command: show configuration protocols bgp | display set
  # - command: show configuration protocols bgp
   
test_routing_options:
  - command: show configuration routing-options | display set
  # - command: show configuration routing-options nat 

