tests_include:
  - test_security_policies_fw
  - test_security_policies_nat

test_security_policies_fw:
  - command: show configuration security policies | display set
  # - command: show configuration security policies
   
test_security_policies_nat:
  - command: show configuration security nat | display set
  # - command: show configuration security nat 

