---
###################################################################################
#
# Copyright 2020 Juniper Networks, Inc. All rights reserved.
# Licensed under the Juniper Networks Script Software License (the "License").
# You may not use this script file except in compliance with the License, which is 
# located at http://www.juniper.net/support/legal/scriptlicense/
# Unless required by applicable law or otherwise agreed to in writing by the 
# parties, software distributed under the License is distri buted on an 
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express 
# or implied.
#
##################################################################################
#
# Author        : Subrata Mazumdar, Juniper Networks Professional Services
# Contact       : subratam@juniper.net
# Company       : Juniper Networks
#
#
# Description   : Run this plabook to backup the NS-nodes based on the hostname(ip-address)
#
#                 How to run this playbook:
#                   ansible-playbook -vvv netdev_junos_config_deploy_qfx.yml
#
#


- name: Compare config diff  files between devices
  hosts: localhost
  connection: local
  become: false
  gather_facts: false
  vars :
    device_ip_list: "{{ groups[device_group_name] |  map('extract', hostvars, 'ansible_host')  | list }}"
    device_name_list: "{{ groups[device_group_name] |  map('extract', hostvars, 'inventory_hostname')  | list }}"
  roles:
  - Juniper.junos


  tasks:

  - name: Display input parameters for this play 
    debug: 
      msg: "device_group_name: {{ device_group_name }} device_ip_list: {{ device_ip_list }}  device_name_list: {{ device_name_list }}"


  # Generate device config diff report  
  - include_role :
      name : junos-config-diff-report 
  #   vars:
  #     junos_config_filename_prefix: "{{ dqenet_device_junos_config_filename_prefix }}"
   
  # - name: Forced Fail
  #   fail:

# end-name


