---
###################################################################################
#
# Copyright 2020 Juniper Networks, Inc. All rights reserved.
# Licensed under the Juniper Networks Script Software License (the "License").
# You may not use this script file except in compliance with the License, which is 
# located at http://www.juniper.net/support/legal/scriptlicense/
# Unless required by applicable law or otherwise agreed to in writing by the 
# parties, software distributed under the License is distri buted on an 
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express 
# or implied.
#
##################################################################################
#
# Author        : Subrata Mazumdar, Juniper Networks Professional Services
# Contact       : subratam@juniper.net
# Company       : Juniper Networks
#
#
# Description   : Run this plabook to backup the NS-nodes based on the hostname(ip-address)
#
#                 How to run this playbook:
#                   ansible-playbook -vvv netdev_junos_config_deploy_qfx.yml
#
#


- name: generate Junos config file based config fraggment templates
  # hosts: "{{ device_group_name | default(cluster_fabric_qfx_devices, true) }}"
  # hosts: cluster_fabric_qfx_devices
  hosts: all
  gather_facts: false
  connection: local
  serial: 1
  # serial: "{{ ns_install_batch_size | default('100%') }}" # Must override from CLI - specifying in group_vars/all.yml does not work 
  # vars_files:
  #   - "{{ dqenet_device_config_file }}"
  vars:
  roles:
  - Juniper.junos


  tasks:

  # Plecase holder for custom parameters for device config 
  - name: Set path for junos_dev_config_params file
    when: false
    set_fact:
      dqenet_device_config_params_filepath : "{{ dqenet_junos_dev_config_dir }}/{{ dqenet_junos_dev_config_params_filename }}"
  - name: Load JUNOS Device config params file
    when: false
    include_vars:
      file: "{{ dqenet_device_config_params_filepath }}"
      name: junos_device_config_params


  # Genereted device config file based config fragment temp[lates  
  - include_role :
      name : qfx-junos-config 
    vars:
      junos_config_filename_prefix: "{{ dqenet_device_junos_config_filename_prefix }}"
      dev_cli_user_name: "{{ dqenet_device_junos_cli_username }}"


  - name: dump dqenet_device_junos_junos_config_params var
    debug:
      msg: "host : {{ inventory_hostname }} device_junos_config_file_local: {{ device_junos_config_file_local }} dqenet_device_junos_cli_username: {{ dqenet_device_junos_cli_username }} dqenet_device_junos_cli_password: {{ dqenet_device_junos_cli_password }}"

  # Deploy device config file 
  - include_role :
      name : junos-config-deploy 
    vars:
      junos_config_filename_prefix: "{{ dqenet_device_junos_config_filename_prefix }}"
      dev_cli_user_name: "{{ dqenet_device_junos_cli_username }}"
      dev_cli_user_password: "{{ dqenet_device_junos_cli_password }}"
      dev_cli_user_privkey_file: "{{ dqenet_device_junos_cli_user_privkey_file }}"
      dev_config_commit_check: true
      dev_config_commit: true
      # dev_config_commit_check: "{{ dqenet_device_junos_commit_check }}"
      # dev_config_commit: "{{ dqenet_device_junos_commit }}"
      
  # - name: Forced Fail
  #   fail:

# end-name


