---
###################################################################################
#
# Copyright 2020 Juniper Networks, Inc. All rights reserved.
# Licensed under the Juniper Networks Script Software License (the "License").
# You may not use this script file except in compliance with the License, which is 
# located at http://www.juniper.net/support/legal/scriptlicense/
# Unless required by applicable law or otherwise agreed to in writing by the 
# parties, software distributed under the License is distri buted on an 
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express 
# or implied.
#
##################################################################################
#
# Author        : Subrata Mazumdar, Juniper Networks Professional Services
# Contact       : subratam@juniper.net
# Company       : Juniper Networks
#
#
# Description   : 
#
#
#
# How to run this playbook:
#   ansible-playbook -vvv fwvnfmgr_stack_status_play.yml  -e vnf_stack_name=STACK_201710261703_ZRDM3FRWL98OAM 
#
- name: Verify VMs associated with FW-VNF stacks are reachable
  connection: local
  hosts: localhost
  become: false
  gather_facts: false
  # strategy: debug
  #
  vars :
    stack_server_name_query: "data.output"
    stack_server_mgmtip_list: []

  environment:
      OS_TENANT_NAME: "{{ os_tenant_name }}" 
      OS_PROJECT_NAME: "{{ os_tenant_name }}" 

  tasks:

  # Find and initiilie the name and mgmt-ip of the service VMs of stacks for VNF
  # Result is returned on the vnfstack_action_result variable 
  - name: get name-mgmtip dict of all the servers associated with stacks for  VNF 
    include_role :
      name : vnfstack 
    vars:
      action: "show-stack-server-name-mgmtip-list"
      stack_name: "{{ vnf_stack_name }}"
      server_mgmt_vn_name: "{{ vnf_mgmt_vn_name }}"
      server_image_name: "{{ vnf_svm_image_name }}"
      # server_image_uuid: "{{ vnf_svm_image_uuid }}"
      # wait_for_stack: true
      # os_tenant_name: "{{ stack_project_name }}"
    # register: stack_server_name_mgmtip_list

  - name: save server name-mgmtip list 
    set_fact:
      stack_server_name_mgmtip_list: "{{ vnfstack_action_result | json_query('data.output') }}"
  - name: set fact for server names
    set_fact:
      stack_server_name_list: "{{ stack_server_name_mgmtip_list | json_query('[*].name') }}"
  - name: set fact for server mgmt-ips
    set_fact:
      stack_server_mgmtip_list: "{{ stack_server_name_mgmtip_list | json_query('[*].ip_address') }}"

# end-name
