
# TODO : Must change CONFIG_FRAGMENT_TEMPLATE_REPO_DIR
export CONFIG_FRAGMENT_TEMPLATE_REPO_DIR=${CONFIG_FRAGMENT_TEMPLATE_REPO_DIR:=`pwd`}
export CONFIG_FRAGMENT_TEMPLATE_BASE_DIR=${CONFIG_FRAGMENT_TEMPLATE_BASE_DIR:=${CONFIG_FRAGMENT_TEMPLATE_REPO_DIR}/templates}
export CONFIG_FRAGMENT_MODEL_DIR=${CONFIG_FRAGMENT_TEMPLATE_BASE_DIR:=${CONFIG_FRAGMENT_TEMPLATE_REPO_DIR}/files}
export DQNET_DEVICE_DATA_DIR=${DQNET_DEVICE_DATA_DIR:=/var/tmp/DQE_DATA}
export JSNAPY_OUTPUT_DIR=${JSNAPY_OUTPUT_DIR:=${DQNET_DEVICE_DATA_DIR}/jsnapy}
